import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AuthListener from "@/components/AuthListener";
import LoginToast from "@/components/LoginToast";


export const metadata = {
  title: "Price Drop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster richColors position="top-right" />
        <LoginToast />
        <AuthListener />
        {children}  
        
        
      </body>
    </html>
  );
}
