import "./globals.css";
import { Toaster } from "sonner";
import LoginToast from "@/components/LoginToast";
import { AuthProvider } from "@/components/AuthProvider";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata = {
  title: "Price Drop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <Toaster richColors position="top-right" />
            <LoginToast />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}